apiVersion: v1
kind: Service
metadata:
  name: trt-converter
  namespace: default
spec:
  ports:
  - name: http-flask
    port: 5000
    protocol: TCP
  selector:
    app: trt-converter
  sessionAffinity: None
  type: LoadBalancer