apiVersion: apps/v1
kind: Deployment
metadata:
  name: tritonserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tritonserver
  template:
    metadata:
      labels:
        app: tritonserver
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: tritonserver
        image: nvcr.io/nvidia/tritonserver:{{ Values.tritonTag }}-py3
        command:
        - /bin/bash
        args:
        - -c
        - LD_LIBRARY_PATH="$LD_LIBRARY_PATH:{{ Values.nvPaths }}" bin/tritonserver --model-repository {{ Values.repo }} --repository-poll-secs 30
        resources:
          limits:
            nvidia.com/gpu: {{ Values.numGPUs }}
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 8001
          protocol: TCP
        - containerPort: 8002
          protocol: TCP
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4